export const todos = [
  {
    id: 1,
    title: "Buy groceries",
    description: "Purchase milk, bread, eggs, and fruits",
    category: "Finance",
    completed: false,
    priority: "medium",
    startedAt: "2025-01-15",
    dueAt: "2025-01-16",
  },
  {
    id: 2,
    title: "Study JavaScript",
    description: "Practice DOM manipulation and array methods",
    category: "Study",
    completed: false,
    priority: "high",
    startedAt: "2025-01-14",
    dueAt: "2025-01-18",
  },
  {
    id: 3,
    title: "Clean the house",
    description: "Sweep, mop, and arrange the living room",
    category: "Personal",
    completed: true,
    priority: "low",
    startedAt: "2025-01-10",
    dueAt: "2025-01-11",
  },
  {
    id: 4,
    title: "Finish portfolio website",
    description: "Complete landing page and contact form",
    category: "Project",
    completed: false,
    priority: "high",
    startedAt: "2025-01-12",
    dueAt: "2025-01-25",
  },
  {
    id: 5,
    title: "Go to the gym",
    description: "Leg day workout session",
    category: "Fitness",
    completed: false,
    priority: "medium",
    startedAt: "2025-01-15",
    dueAt: "2025-01-15",
  },
  {
    id: 6,
    title: "Pay electricity bill",
    description: "Settle monthly power bill online",
    category: "Finance",
    completed: true,
    priority: "high",
    startedAt: "2025-01-05",
    dueAt: "2025-01-07",
  },
  {
    id: 7,
    title: "Read a book",
    description: "Finish Chapter 3 of Atomic Habits",
    category: "Personal",
    completed: false,
    priority: "low",
    startedAt: "2025-01-13",
    dueAt: "2025-01-20",
  },
  {
    id: 8,
    title: "Plan weekly schedule",
    description: "Organize tasks for next week",
    category: "Personal",
    completed: false,
    priority: "medium",
    startedAt: "2025-01-16",
    dueAt: "2025-01-17",
  },
  {
    id: 9,
    title: "Call Mom",
    description: "Check in and catch up",
    category: "Personal",
    completed: false,
    priority: "low",
    startedAt: "2025-01-15",
    dueAt: "2025-01-15",
  },
  {
    id: 10,
    title: "Update resume",
    description: "Add new skills and recent experience",
    category: "Learning",
    completed: false,
    priority: "high",
    startedAt: "2025-01-14",
    dueAt: "2025-01-22",
  },
];
